[package]
name = "cosmic-applibrary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cascade = "1.0.0"
gtk4 = { version = "0.4.7", features = ["v4_4"] }
gdk4-wayland = { version = "0.4.2", features = [ "wayland_crate" ], optional = true }
gdk4-x11 = { version = "0.4.2", features = [ "xlib" ] }
wayland-client = { version = "0.29.4", optional = true }
wayland-protocols = { version = "0.29.4", features = [ "client", "unstable_protocols" ], optional = true }
x11 = { version = "2.19.1", features = ["xlib"] }
libcosmic = { git = "https://github.com/pop-os/libcosmic" }
relm4-macros = { git = "https://github.com/AaronErhardt/Relm4" }
serde = "1.0.134"
serde_json = "1.0.75"
tokio = { version = "1.15.0", features = ["sync"] }
once_cell = "1.9.0"
xdg = "2.4.0"
cosmic-theme = { path = "../cosmic-theme" }

[profile.release]
incremental = true
debug = 1

[features]
layer-shell = ["gdk4-wayland", "wayland-client", "wayland-protocols"]
